/*
 * generated by Xtext
 */
package org.collaboration;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class CollaborationRuntimeModule extends org.collaboration.AbstractCollaborationRuntimeModule {

}
