/*
 * generated by Xtext
 */
package org.collaboration;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class CollaborationStandaloneSetup extends CollaborationStandaloneSetupGenerated{

	public static void doSetup() {
		new CollaborationStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

